require 'pathname'

target_file = 'src/services/weiwo/builtin-patches/index.js'
target_folder = 'src/services'

ocs_sources = Dir.glob("src/ocs/*.ocs")
ocs_modules = ocs_sources.map{|source| Pathname.new(target_folder).join("#{File.basename(source, '.ocs')}/index.js").to_s }

task :default => [
  *ocs_modules,
]

ocs_modules.each_with_index do |ocs_module, index|
    file ocs_module => [ ocs_sources[index] ] do |t|
        source = t.prerequisites[0]
        target = t.name

        puts "source: #{source}"
        puts "target: #{target}"

        sh "node -r esm ./src/parsers/ocs-runner.js -compile #{source} > tmp.js"
        sh "mv tmp.js #{target}"
    end
end

